name: "discord-clone-remix"

version: "3.1"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: discord_clone
    ports:
      - 6578:5432

  redis:
    image: redis:latest
    ports:
      - 6379:6379
